---
- name: Deploy Interactive Scientific Calculator
  hosts: localhost
  connection: local
  become: yes 
  
  tasks:
    - name: Pull the latest image from Docker Hub
      community.docker.docker_image:
        name: prasanna07e/scientific-calculator
        tag: latest
        source: pull

    - name: Remove old container (if it exists)
      community.docker.docker_container:
        name: scientific_calc_container
        state: absent
        force_kill: false
        
    - name: Create and start the calculator container
      community.docker.docker_container:
        name: scientific_calc_container
        image: prasanna07e/calculator-app_m:latest
        state: started
        interactive: yes
        tty: yes
        detach: yes 
        auto_remove: no






